sonar.projectKey=api-spring-local
sonar.projectName=API Spring Local
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.token=squ_33e6266804294e571d4fde598ad4edc8cba3a046
sonar.java.binaries=target/classes